language: rust
rust:
- stable
- beta
- nightly
cache: cargo
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
- osx
- windows
script: cargo build --verbose --release; cargo test --verbose
before_deploy:
- mv target/release/rocfl "target/release/rocfl-$TRAVIS_TAG-$TRAVIS_OS_NAME"
deploy:
  - provider: releases
    skip_cleanup: true
    draft: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable"
      repo: pwinckles/rocfl
      branch: master
    file:
      - target/release/rocfl-*
    api_key:
      secure: msSjsie8Eib0kvoH2K6J/3YMf7mnsbuaAfZ+N7cT5LcXs+n0AWZfqJfRwY39ACxVN8xOFUcZDBn4l3uqaVg6HSLOTMe0MmOgB5xGsF5s7EU0gKkYYuHT9Mrnc0Ubgk+BQfq6L4DlwRO0gVAuDjCF7HhMsLTx8PrVoxYGpMwjGMHg/qbIRypnbbkJsADJt1aUhklwZfPoqwwNZWIomiaxVDqS3VnMPgKGdY7eQNULQcOe6xemoRYhGSoj9RYUk6Y+FP8Cz3h8X05kd+E6WVrW7j/KMXOluee7+as2sB+EpO1aoQPjj/6ZKJSDwWsCc1ddH5Rvw1fTNRu+jWZO9RUG8VQxUdD+ek/qHnhicYIkLJRdvaNAmDObnhgM7G3GnMdHIUuA0VwKTzj1d0+/6SvB98dD4q1E5LJ9MbQfz/IyQ1qAhnwNR75lAM9pRiOUI946u8UmW4o9SWkJ77bBTs/otDS1uxxYr6CwjwPo0UCqE3eUwI/59ydz5jItTTxZbP2y3Z4EhBMK6uJJKleWfHKIG1KYzJ/VJFJh63S6FCh2W/Isn5EvFHOt8PlRc1r+AmC7nj8EUJTwsyq0k2Nt35rEagY99B7x/LdLb7soQbJlAHNpOA/AY2Y6u5B+gASxSfwr/NUg1Qs5G2d42qrjp5KGSv/oJFuRAKd/2adtV3jzjB0=
