[package]
name = "rocfl"
version = "0.1.5"
authors = ["Peter Winckles <pwinckles@pm.me>"]
edition = "2018"
description= "A Rust CLI for OCFL repositories"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/pwinckles/rocfl"
homepage = "https://github.com/pwinckles/rocfl"
documentation = "https://docs.rs/rocfl/"

[[bin]]
name = "rocfl"
path = "src/bin/rocfl.rs"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = "2"
globset = "0.4"
grep = "0.2"
lazy_static = "1.4"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
termcolor = "1.1"
thiserror = "1.0"
