[package]
name = "rocfl"
version = "1.3.3"
authors = ["Peter Winckles <pwinckles@pm.me>"]
edition = "2018"
description= "A Rust CLI for OCFL repositories"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/pwinckles/rocfl"
homepage = "https://github.com/pwinckles/rocfl"
documentation = "https://docs.rs/rocfl/"

[[bin]]
name = "rocfl"
path = "src/bin/rocfl.rs"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = "2"
globset = "0.4"
grep-matcher = "0.1"
grep-searcher = "0.1"
grep-regex = "0.1"
lazy_static = "1.4"
natord = "1"
regex = "1"
rusoto_core = { version = "0.45", default_features = false, features =["rustls"] }
rusoto_credential = "0.45"
rusoto_s3 = { version = "0.45", default_features = false, features = ["rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
thiserror = "1.0"
tokio = "0.2"
unicode-width = "0.1"
urlencoding = "1.1"

[dev-dependencies]
maplit = "1"