[package]
name = "roc"
version = "0.1.0"
authors = ["Peter Winckles <pwinckles@pm.me>"]
edition = "2018"
description= "A Rust CLI for OCFL repositories"
license = "MIT OR Apache-2.0"

[[bin]]
name = "roc"
path = "src/bin/roc.rs"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
termcolor = "1.1"
thiserror = "1.0"
