---
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        UID: ${UID:-1001}
        GID: ${GID:-1001}
    hostname: app.local
    networks:
      default:
        aliases: ["app"]
    volumes:
      - ./:/app
    command:
      - "sleep"
      - "infinity"
networks:
  default:
