---
name: Build rocfl image

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions

jobs:
  build:
    name: rocfl
    runs-on: ubuntu-latest
    # Ensure this job only executed for 'mlibrary/rocfl'
    if: github.repository == 'mlibrary/rocfl'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push rocfl image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64/v8
          push: true
          tags: 'ghcr.io/mlibrary/rocfl/rocfl:latest, ghcr.io/mlibrary/rocfl/rocfl:${{ github.sha }}'
          file: Dockerfile
